### ISSUE TITLE
Squished image in model-retraining recipe

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/kafka-tutorials#1212]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/141130/160150894-2622ab05-36a4-48f0-b9c0-db8b40c9be37.png">

cc @ybyzek

**Comment by ybyzek** [comment]
@scott-confluent I think this image is getting stretched vertically because the text description is very long.  If I remove the second paragraph, the image presents correctly

https://developer.confluent.io/tutorials/model-retraining/confluent.html

Is there a way to fix this in the CSS to limit the stretching ratio of the images?
