### ISSUE TITLE
Processing Syslog Data: Pattern Detection and Alerting

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/kafka-tutorials#264]
Enrich and filter syslog data with KSQL to detect anomalies in an infrastructure logging stream.

label: ANOMALY DETECTION

**Comment by awalther28** [comment]
This recipe's technical content is about using a `WHERE` clause which is covered by many kafka tutorials. The average time on page was less than 1 minute in December 2020. Due to the repetitive nature of the content in the recipe, the IA team will not convert this recipe. Again, the technical content is covered in various other KTs.
