### ISSUE TITLE
Sensor Data Enrichment

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/kafka-tutorials#268]
Enrich sensor data and perform joins with KSQL through reading timestamps.

label: EVENT TIME PROCESSING

**Comment by awalther28** [comment]
This recipe focuses on using an arbitrary field for a timestamp, which was already covered in the [event time processing KT](https://github.com/confluentinc/kafka-tutorials/pull/647) @ybyzek did in Q4 2020. Due to the repetitive nature of the content in the recipe, the IA team will not convert the /using-event-time-from-iot-sensor-readings recipe.
