### ISSUE TITLE
Changing Serialization Format: move cards

### ISSUE THREAD

**Issue by ybyzek** [confluentinc/kafka-tutorials#472]
Move https://kafka-tutorials.confluent.io/changing-serialization-format/ksql.html from the card `Apply a function to data` to `Kafka 101`.

The reasoning for proposing this move:

1. Goal of the KT is to change the format of the Kafka topic itself.  Even the KT description says: Consider a topic with events that represent movie releases. The events in the topic are formatted with Avro. In this tutorial, we'll write a program that creates a new topic with the same events, but formatted with Protobuf.   This is more of a 101 capability
2. The KT doesn’t really apply any stream processing “function”, it just creates a new stream
3. Consistency with https://github.com/confluentinc/kafka-tutorials/pull/470 which is also about changing the Kafka topic attributes, and that is Kafka 101
4. Minor point: move some content to Kafka 101 to balance the entries more

**Comment by bbejeck** [comment]
We've refactored the index page since this issue was filed.  The  https://kafka-tutorials.confluent.io/changing-serialization-format/ksql.html is now in the `Manipulating Streams` card and the `Kafka 101` card has been removed, so I'm going to close this issue as resolved by PR https://github.com/confluentinc/kafka-tutorials/pull/683
